"""Change total_price to int

Revision ID: 281b912a991e
Revises: 74d4be6344db
Create Date: 2025-05-29 12:39:29.540477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281b912a991e'
down_revision: Union[str, None] = '74d4be6344db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'total_price',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="total_price::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'total_price',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###
